services:
  web:
    build: .
    ports:
      - "8222:80"
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_ROOT_PASSWORD: passer@12345
      MYSQL_DATABASE: maboutique2
      MYSQL_USER: root
      MYSQL_PASSWORD: passer@12345